
server:
  port: 9507

spring:
  application:
    name: config-server-service

  cloud:
    config:
      server:
        git:
          uri: file://home/WORLDPAY.LOCAL/parihav610/Documents/POC/microservices/git-localconfig-repo
          clone-on-start: true




